// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Philosopher } from "next/font/google";
// import "./globals.css";
// import Footer from "@/components/layout/footer";
// import Header from "@/components/layout/header";
// import BackToTop from "@/components/layout/BackToTop";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const philosopher = Philosopher({
//   weight: ['400', '700'], // specify the weights you need
//   subsets: ['latin'],
//   display: 'swap',
// })

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "deCave",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-[#FAF8FF]`}
//       >
        
//         <div className="relative">

//         <div className="absolute top-2 left-0 right-0 z-50 lg:px-6">
//           <div className="max-w-full mx-auto">
//             <Header/>
//           </div>
//         </div>
//         {children}
//           <BackToTop/>
//         <Footer/>
//         </div>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Philosopher } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import BackToTop from "@/components/layout/BackToTop";
import { NewsletterModal } from "@/components/layout/NewsletterModal";

const philosopher = Philosopher({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-philosopher',
})


export const metadata: Metadata = {
  title: {
    default: "deCave | Exclusive Events & Premium Experiences",
    template: "%s | deCave",
  },
  description:
    "deCave is the official home of exclusive, high-end events. Discover curated nightlife experiences, secure premium tickets, and step into unforgettable moments.",
  keywords: [
    "deCave",
    "exclusive events",
    "luxury nightlife",
    "premium event tickets",
    "VIP events",
    "private events",
    "elite experiences",
    "official event tickets",
  ],
  authors: [{ name: "deCave" }],
  creator: "deCave",
  publisher: "deCave",
  metadataBase: new URL("https://decavemgt.com"),
  openGraph: {
    title: "deCave | Exclusive Events & Premium Experiences",
    description:
      "Official ticket access to deCave’s curated luxury events. Premium vibes, seamless entry, unforgettable nights.",
    url: "https://decavemgt.com",
    siteName: "deCave",
    images: [
      {
        url: "/logo.svg",
        width: 1200,
        height: 630,
        alt: "deCave Luxury Nightlife Experience",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "deCave | Exclusive Events & Premium Experiences",
    description:
      "Step into deCave’s world of curated luxury events and premium nightlife experiences.",
    images: ["/logo.svg"],
  },
  
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.svg" />
      </head>
      <body
        className={`${philosopher.variable} font-philosopher antialiased bg-black text-[#FAF8FF]`}
      >
        
        <div className="relative">

        <div className="absolute top-2 left-0 right-0 z-50 lg:px-6">
          <div className="max-w-full mx-auto">
            <Header/>
          </div>
        </div>
        {children}
          <BackToTop/>
          <NewsletterModal />
        <Footer/>
        </div>
      </body>
    </html>
  );
}